### ISSUE TITLE
incorrect link in course

### ISSUE THREAD

**Issue by jaymoid** [acantril/aws-dev-associate#3]
Hi Adrian, 

Just a heads-up  - the slide notes, on page https://learn.cantrill.io/courses/1101194/lectures/26953794 references:
https://github.com/acantril/aws-dev-associate/blob/main/07-VPC-Basics/03_vpc_subnets/subnets.txt

But it looks like this has moved to:
https://github.com/acantril/aws-dev-associate/blob/main/09-VPCBasics/03_vpc_subnets/subnets.txt

Hope that helps, this is a great course - thanks 👍

**Comment by acantril** [comment]
thanks for this, fixed.
