### ISSUE TITLE
Privacy provider fails provider_testcase::test_userdata_provider_implements_userlist

### ISSUE THREAD

**Issue by bradpasley** [acantril/aws-dev-associate#8]
When running `vendor/bin/phpunit "provider_testcase" privacy/tests/provider_test.php`

The following failure is displayed:
```
There was 1 failure:

1) provider_testcase::test_userdata_provider_implements_userlist with data set "mod_booking" ('mod_booking', 'mod_booking\privacy\provider')
Failed asserting that false is true.

/var/www/site/privacy/tests/provider_test.php:212
/var/www/site/lib/phpunit/classes/advanced_testcase.php:80
phpvfscomposer:///var/www/site/vendor/phpunit/phpunit/phpunit:6
```

Your privacy provider needs to implement `\core_privacy\local\request\core_userlist_provider`
It requires the following methods which you haven't implements:
- 'get_users_in_context'
- 'delete_data_for_users'

**Comment by acantril** [comment]
Did you post this in the wrong place ?

**Comment by bradpasley** [comment]
sorry wrong place.
